name: C/C++ CI

on:
  workflow_dispatch: #ManualTrigger

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
    - uses: threeal/cmake-action@v2.1.0
    - name: Cmake-Build  
      run: |
        cd build
        cmake ..
        cmake --build . --config Release
    - name: Upload executable
      uses: actions/upload-artifact@v4
      with:
        name: gameOfLife-${{ matrix.os }}
        path: build/*
